apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  annotations:
    volume.beta.kubernetes.io/storage-class: xxxxxxx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: redis
    spec:
      containers:
      - name: redis-service
        image: redis
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: TZ
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: redis
spec:
  type: LoadBalancer
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    application: redis
